// Build script for oasis-skin: generates built-in skin loader functions from
// TOML skin directories in `../../skins/`.
//
// For each skin directory that contains `skin.toml`, `layout.toml`,
// `features.toml`, `theme.toml`, and `strings.toml`, this generates a Rust
// function `gen_{name}_skin() -> Result<Skin>` that loads the skin via
// `include_str!` + `Skin::from_toml_full()`. PNG images in the skin's
// `assets/` subdirectory are embedded with `include_bytes!` and registered
// via `Skin::add_asset_png`.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let skins_dir = Path::new(&manifest_dir).join("../../skins");
    let out_dir = env::var("OUT_DIR")?;
    let out_path = Path::new(&out_dir).join("builtin_generated.rs");

    // Re-run if any skin file changes.
    println!("cargo::rerun-if-changed={}", skins_dir.display());

    // (dir_name, fn_name, png asset file names, font asset file names)
    #[allow(clippy::type_complexity)]
    let mut skins: Vec<(String, String, Vec<String>, Vec<String>)> = Vec::new();

    if let Ok(entries) = fs::read_dir(&skins_dir) {
        let mut dirs: Vec<_> = entries.filter_map(|e| e.ok()).collect();
        dirs.sort_by_key(|e| e.file_name());

        for entry in &dirs {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }

            let dir_name = entry.file_name().to_string_lossy().to_string();

            // Check that all required TOML files exist.
            let required = [
                "skin.toml",
                "layout.toml",
                "features.toml",
                "theme.toml",
                "strings.toml",
            ];
            let all_present = required.iter().all(|f| path.join(f).exists());
            if !all_present {
                // Register each file for change detection anyway.
                for f in &required {
                    let fp = path.join(f);
                    println!("cargo::rerun-if-changed={}", fp.display());
                }
                continue;
            }

            // Register individual files for change detection.
            for f in &required {
                let fp = path.join(f);
                println!("cargo::rerun-if-changed={}", fp.display());
            }

            // Collect PNG and font assets from the skin's assets/ subdirectory.
            let assets_dir = path.join("assets");
            let mut assets: Vec<String> = Vec::new();
            let mut fonts: Vec<String> = Vec::new();
            if let Ok(asset_entries) = fs::read_dir(&assets_dir) {
                for ae in asset_entries.filter_map(|e| e.ok()) {
                    let ap = ae.path();
                    let ext_is = |wanted: &str| {
                        ap.extension()
                            .is_some_and(|ext| ext.eq_ignore_ascii_case(wanted))
                    };
                    if ext_is("png") {
                        println!("cargo::rerun-if-changed={}", ap.display());
                        assets.push(ae.file_name().to_string_lossy().to_string());
                    } else if ext_is("ttf") || ext_is("otf") {
                        println!("cargo::rerun-if-changed={}", ap.display());
                        fonts.push(ae.file_name().to_string_lossy().to_string());
                    }
                }
                assets.sort();
                fonts.sort();
            }

            // Convert directory name to a valid Rust identifier.
            // e.g., "retro-cga" -> "retro_cga"
            let fn_name = dir_name.replace('-', "_");
            skins.push((dir_name, fn_name, assets, fonts));
        }
    }

    let mut out = fs::File::create(&out_path)?;

    writeln!(
        out,
        "// Auto-generated skin loader functions from `skins/` TOML directories."
    )?;
    writeln!(out, "// Generated by build.rs -- do not edit manually.")?;
    writeln!(out)?;
    writeln!(out, "use oasis_types::error::Result;")?;
    writeln!(out)?;
    writeln!(out, "use crate::loader::Skin;")?;
    writeln!(out)?;

    for (dir_name, fn_name, assets, fonts) in &skins {
        let no_assets = assets.is_empty() && fonts.is_empty();
        writeln!(out, "/// Load the `{dir_name}` skin (generated from TOML).")?;
        writeln!(out, "#[allow(dead_code)]")?;
        writeln!(out, "pub fn gen_{fn_name}_skin() -> Result<Skin> {{")?;
        if no_assets {
            // No assets: the parse result is the tail expression.
            writeln!(out, "    Skin::from_toml_full(")?;
        } else {
            writeln!(out, "    let mut skin = Skin::from_toml_full(")?;
        }
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/skin.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/layout.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/features.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/theme.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/strings.toml\")),"
        )?;
        writeln!(out, "    ){}", if no_assets { "" } else { "?;" })?;
        for asset in assets {
            writeln!(
                out,
                "    skin.add_asset_png(\"assets/{asset}\", \
                 include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
                 \"/../../skins/{dir_name}/assets/{asset}\")))?;"
            )?;
        }
        for font in fonts {
            writeln!(
                out,
                "    skin.add_asset_font(\"assets/{font}\", \
                 include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
                 \"/../../skins/{dir_name}/assets/{font}\")).to_vec());"
            )?;
        }
        if !no_assets {
            writeln!(out, "    Ok(skin)")?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    // Generate a list of generated skin names.
    writeln!(out, "/// Names of skins generated from TOML directories.")?;
    writeln!(out, "#[allow(dead_code)]")?;
    writeln!(out, "pub const GENERATED_SKIN_NAMES: &[&str] = &[")?;
    for (dir_name, _, _, _) in &skins {
        writeln!(out, "    \"{dir_name}\",")?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;

    // Generate a dispatch function.
    writeln!(out, "/// Load a generated skin by name.")?;
    writeln!(out, "#[allow(dead_code)]")?;
    writeln!(
        out,
        "pub fn load_generated_skin(name: &str) -> Option<Result<Skin>> {{"
    )?;
    writeln!(out, "    match name {{")?;
    for (dir_name, fn_name, _, _) in &skins {
        writeln!(out, "        \"{dir_name}\" => Some(gen_{fn_name}_skin()),")?;
    }
    writeln!(out, "        _ => None,")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;

    Ok(())
}
