// Build script for oasis-skin: generates built-in skin loader functions from
// TOML skin directories in `../../skins/`.
//
// For each skin directory that contains `skin.toml`, `layout.toml`,
// `features.toml`, `theme.toml`, and `strings.toml`, this generates a Rust
// function `gen_{name}_skin() -> Result<Skin>` that loads the skin via
// `include_str!` + `Skin::from_toml_full()`.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let skins_dir = Path::new(&manifest_dir).join("../../skins");
    let out_dir = env::var("OUT_DIR")?;
    let out_path = Path::new(&out_dir).join("builtin_generated.rs");

    // Re-run if any skin file changes.
    println!("cargo::rerun-if-changed={}", skins_dir.display());

    let mut skins: Vec<(String, String)> = Vec::new(); // (dir_name, fn_name)

    if let Ok(entries) = fs::read_dir(&skins_dir) {
        let mut dirs: Vec<_> = entries.filter_map(|e| e.ok()).collect();
        dirs.sort_by_key(|e| e.file_name());

        for entry in &dirs {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }

            let dir_name = entry.file_name().to_string_lossy().to_string();

            // Check that all required TOML files exist.
            let required = [
                "skin.toml",
                "layout.toml",
                "features.toml",
                "theme.toml",
                "strings.toml",
            ];
            let all_present = required.iter().all(|f| path.join(f).exists());
            if !all_present {
                // Register each file for change detection anyway.
                for f in &required {
                    let fp = path.join(f);
                    println!("cargo::rerun-if-changed={}", fp.display());
                }
                continue;
            }

            // Register individual files for change detection.
            for f in &required {
                let fp = path.join(f);
                println!("cargo::rerun-if-changed={}", fp.display());
            }

            // Convert directory name to a valid Rust identifier.
            // e.g., "retro-cga" -> "retro_cga"
            let fn_name = dir_name.replace('-', "_");
            skins.push((dir_name, fn_name));
        }
    }

    let mut out = fs::File::create(&out_path)?;

    writeln!(
        out,
        "// Auto-generated skin loader functions from `skins/` TOML directories."
    )?;
    writeln!(out, "// Generated by build.rs -- do not edit manually.")?;
    writeln!(out)?;
    writeln!(out, "use oasis_types::error::Result;")?;
    writeln!(out)?;
    writeln!(out, "use crate::loader::Skin;")?;
    writeln!(out)?;

    for (dir_name, fn_name) in &skins {
        writeln!(out, "/// Load the `{dir_name}` skin (generated from TOML).")?;
        writeln!(out, "#[allow(dead_code)]")?;
        writeln!(out, "pub fn gen_{fn_name}_skin() -> Result<Skin> {{")?;
        writeln!(out, "    Skin::from_toml_full(")?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/skin.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/layout.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/features.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/theme.toml\")),"
        )?;
        writeln!(
            out,
            "        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../skins/{dir_name}/strings.toml\")),"
        )?;
        writeln!(out, "    )")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    // Generate a list of generated skin names.
    writeln!(out, "/// Names of skins generated from TOML directories.")?;
    writeln!(out, "#[allow(dead_code)]")?;
    writeln!(out, "pub const GENERATED_SKIN_NAMES: &[&str] = &[")?;
    for (dir_name, _) in &skins {
        writeln!(out, "    \"{dir_name}\",")?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;

    // Generate a dispatch function.
    writeln!(out, "/// Load a generated skin by name.")?;
    writeln!(out, "#[allow(dead_code)]")?;
    writeln!(
        out,
        "pub fn load_generated_skin(name: &str) -> Option<Result<Skin>> {{"
    )?;
    writeln!(out, "    match name {{")?;
    for (dir_name, fn_name) in &skins {
        writeln!(out, "        \"{dir_name}\" => Some(gen_{fn_name}_skin()),")?;
    }
    writeln!(out, "        _ => None,")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;

    Ok(())
}
