[package]
name = "oasis-video-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
oasis-video = { path = "..", default-features = false }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_demux_lite"
path = "fuzz_targets/fuzz_demux_lite.rs"
doc = false

[[bin]]
name = "fuzz_avcc_to_annex_b"
path = "fuzz_targets/fuzz_avcc_to_annex_b.rs"
doc = false
