# XP Luna features
dashboard = true
terminal = true
file_browser = true
browser = true
window_manager = true
dashboard_pages = 1
icons_per_page = 15
grid_cols = 5
grid_rows = 3
start_menu = true
show_version = false
show_tabs = false
clock_in_bottombar = true
transition_fade_frames = 12
transition_slide_frames = 16
