//! Default implementation for `ActiveTheme`.
//!
//! Returns legacy defaults identical to the original `theme.rs` constants.

use oasis_types::backend::Color;

use super::{
    ActiveTheme, AppScreenTheme, BarTheme, IconTheme, OskTheme, ScrollbarTheme, StartMenuTheme,
    ToastTheme, WallpaperTheme,
};

impl Default for ActiveTheme {
    /// Returns legacy defaults identical to `theme.rs` constants.
    fn default() -> Self {
        Self {
            bar: BarTheme {
                statusbar_bg: Color::rgba(0, 0, 0, 80),
                bg: Color::rgba(0, 0, 0, 90),
                separator_color: Color::rgba(255, 255, 255, 50),
                battery_color: Color::rgb(120, 255, 120),
                version_color: Color::WHITE,
                clock_color: Color::WHITE,
                url_color: Color::rgb(200, 200, 200),
                usb_color: Color::rgb(140, 140, 140),
                tab_active_fill: Color::rgba(255, 255, 255, 30),
                tab_inactive_fill: Color::rgba(0, 0, 0, 0),
                tab_active_alpha: 180,
                tab_inactive_alpha: 60,
                media_tab_active: Color::WHITE,
                media_tab_inactive: Color::rgb(170, 170, 170),
                pipe_color: Color::rgba(255, 255, 255, 60),
                r_hint_color: Color::rgba(255, 255, 255, 140),
                category_label_color: Color::rgb(220, 220, 220),
                page_dot_active: Color::rgba(255, 255, 255, 200),
                page_dot_inactive: Color::rgba(255, 255, 255, 50),
                statusbar_gradient_top: None,
                statusbar_gradient_bottom: None,
                gradient_top: None,
                gradient_bottom: None,
                text_shadow: false,
                text_shadow_color: Color::rgba(0, 0, 0, 128),
                version_text: "Version 0.1".to_string(),
                category_label: "OSS".to_string(),
                url_text: String::new(),
                tab_active_stroke: Color::rgba(255, 255, 255, 180),
                tab_inactive_stroke: Color::rgba(255, 255, 255, 60),
                tab_texture_active: None,
                tab_texture_inactive: None,
            },
            icon: IconTheme {
                body_color: Color::rgb(250, 250, 248),
                fold_color: Color::rgb(210, 210, 205),
                outline_color: Color::rgba(255, 255, 255, 180),
                shadow_color: Color::rgba(0, 0, 0, 70),
                label_color: Color::rgba(255, 255, 255, 230),
                label_shadow: Some(Color::rgba(0, 0, 0, 120)),
                cursor_color: Color::rgba(255, 255, 255, 90),
                border_radius: 4,
                cursor_border_radius: 6,
                cursor_stroke_width: 2,
                style: "document".to_string(),
                cursor_style: "stroke".to_string(),
                shadow_level: 1,
                vector_preset: "altimit".to_string(),
                idle_float: false,
                float_amplitude: 2.0,
                float_speed: 0.04,
                spin_enabled: false,
                spin_speed: 0.03,
                pulse_enabled: false,
                pulse_speed: 0.06,
                blink_enabled: false,
                blink_interval: 45,
                container_style: "none".to_string(),
                container_padding: 3,
            },
            menu: StartMenuTheme {
                panel_bg: Color::rgba(20, 20, 35, 220),
                panel_gradient_top: None,
                panel_gradient_bottom: None,
                panel_border: Color::rgba(255, 255, 255, 40),
                item_text: Color::rgb(220, 220, 220),
                item_text_active: Color::WHITE,
                highlight_color: Color::rgba(50, 100, 200, 80),
                button_bg: Color::rgba(50, 100, 200, 200),
                button_text: Color::WHITE,
                panel_border_radius: 4,
                panel_shadow_level: 1,
                layout_mode: "grid".to_string(),
                button_label: "START".to_string(),
                button_width: 48,
                button_height: 18,
                button_shape: "pill".to_string(),
                panel_width: 200,
                columns: 2,
                button_gradient_top: None,
                button_gradient_bottom: None,
                header_text: None,
                header_bg: Color::rgba(30, 30, 50, 240),
                header_text_color: Color::WHITE,
                header_height: 0,
                footer_enabled: false,
                footer_bg: Color::rgba(30, 30, 50, 240),
                footer_text_color: Color::WHITE,
                footer_height: 0,
                item_icon_size: 14,
                item_row_height: 22,
                item_colors: vec![
                    Color::rgb(70, 130, 180),
                    Color::rgb(60, 179, 113),
                    Color::rgb(218, 165, 32),
                    Color::rgb(186, 85, 211),
                    Color::rgb(100, 149, 237),
                    Color::rgb(205, 92, 92),
                ],
                pad_inner: 8,
                footer_text: "Log Off  Shut Down".to_string(),
                button_x: 4,
                panel_x: 2,
                item_separator: false,
                item_separator_color: Color::rgba(255, 255, 255, 40),
            },
            app: AppScreenTheme {
                bg: Color::rgb(12, 12, 20),
                divider: Color::rgb(60, 60, 80),
                selected_text: Color::rgb(100, 200, 255),
                text: Color::rgb(180, 180, 200),
                dim_text: Color::rgb(100, 100, 130),
                title_bar_bg: Color::rgb(30, 50, 90),
                title_bar_text: Color::WHITE,
                title_bar_height: 22,
                terminal_output_color: Color::rgb(204, 204, 204),
                terminal_prompt_color: Color::rgb(0, 255, 0),
                input_border_radius: 3,
                selected_bg: Color::rgba(50, 100, 200, 40),
                selection_border_radius: 2,
                selection_accent_color: Color::rgba(50, 100, 200, 128),
                title_bar_gradient_top: None,
                title_bar_gradient_bottom: None,
                title_bar_text_shadow: false,
                title_bar_text_shadow_color: Color::rgba(0, 0, 0, 128),
            },
            osk: OskTheme {
                key_bg: Color::rgba(20, 20, 40, 220),
                key_text: Color::WHITE,
                key_focus: Color::rgb(100, 200, 255),
                key_active: Color::rgb(60, 100, 180),
                key_dim_text: Color::rgb(150, 150, 180),
            },
            scrollbar: ScrollbarTheme {
                track_color: Color::rgba(255, 255, 255, 20),
                thumb_color: Color::rgba(255, 255, 255, 100),
                thumb_hover_color: Color::rgba(255, 255, 255, 160),
                width: 6,
                border_radius: 3,
            },
            wallpaper: WallpaperTheme {
                style: "gradient".to_string(),
                stops: vec![
                    Color::rgb(245, 110, 15),
                    Color::rgb(255, 230, 30),
                    Color::rgb(230, 245, 40),
                    Color::rgb(140, 235, 50),
                    Color::rgb(200, 252, 130),
                ],
                wave: true,
                wave_intensity: 1.0,
                angle: 0.0,
                grid_spacing: 16,
                grid_color: Color::rgba(255, 255, 255, 20),
                noise_intensity: 0.3,
                animated: false,
                source: None,
                fit: "cover".to_string(),
            },
            toast: ToastTheme {
                info_bg: Color::rgba(50, 100, 200, 220),
                success_bg: Color::rgba(60, 180, 100, 220),
                error_bg: Color::rgba(255, 68, 68, 220),
                warning_bg: Color::rgba(230, 170, 40, 220),
                text_color: Color::WHITE,
                border_radius: 4,
                ttl: 180,
                text_shadow: false,
                shadow_level: 1,
                fade_frames: 10,
                margin: 8,
                height: 24,
                width_fraction: 0.333,
                gap: 4,
                slide_in: true,
            },
            background_layers: Vec::new(),
            chrome_layers: Vec::new(),
            image_layers: Vec::new(),
            background_max_layers: 8,
            background_reduced_motion: false,
            background_complexity_budget: 200,
            entrance_style: "none".to_string(),
            entrance_duration_ms: 200,
            entrance_stagger_ms: 30,
            focus_scale: 1.0,
            focus_glow: false,
            focus_glow_color: Color::rgba(100, 200, 255, 100),
            taskbar_height: 20,
            taskbar_bg: Color::rgba(0, 0, 0, 120),
            taskbar_gradient_top: None,
            taskbar_gradient_bottom: None,
            taskbar_btn_active: Color::rgba(60, 120, 200, 120),
            taskbar_btn_inactive: Color::rgba(255, 255, 255, 20),
            taskbar_btn_minimized: Color::rgba(255, 255, 255, 10),
            taskbar_btn_hover: Color::rgba(255, 255, 255, 40),
            taskbar_text_color: Color::rgba(255, 255, 255, 220),
            taskbar_separator: Color::rgba(255, 255, 255, 50),
            taskbar_indicator: Color::rgb(80, 160, 255),
            grid_padding_x: 16,
            grid_padding_y: 6,
            terminal_border_radius: 4,
            statusbar_height: 24,
            bottombar_height: 24,
            tab_row_height: 18,
            icon_width: 42,
            icon_height: 52,
            font_small: 8,
            tab_w: 45,
            tab_h: 16,
            tab_gap: 4,
            tab_start_x: 34,
            pipe_gap: 5,
            r_hint_w: 28,
            icon_stripe_h: 12,
            icon_fold_size: 10,
            icon_gfx_h: 22,
            icon_gfx_pad: 4,
            icon_label_pad: 4,
            tab_w_override: None,
            tab_h_override: None,
            tab_gap_override: None,
            tab_start_x_override: None,
            screen_w: 480,
            screen_h: 272,
            clear_color: Color::rgb(10, 10, 18),
            terminal_line_height: 16,
            cursor_scale: 1,
            cursor_texture: None,
            cursor_hotspot: (0, 0),
            transition_fade_color: Color::BLACK,
            transition_entrance: "fade".to_string(),
            transition_entrance_frames: 45,
            transition_page_style: "slide".to_string(),
            transition_easing: String::new(),
            focus_ring_color: Color::rgba(100, 200, 255, 180),
            focus_ring_width: 2,
            focus_ring_offset: 2,
            font_body: 12,
            font_hint: 10,
            font_heading: 14,
            font_scale: 1.0,
            terminal_cursor_blink_rate: 30,
            cursor_lerp_speed: 0.35,
            page_slide_duration: 6,
            start_menu_anim_speed: 0.25,
            press_flash_duration: 6,
            cursor_pad: 3,
            press_flash_lighten: 0.25,
            app_selection_lerp_speed: 0.25,
            page_dot_lerp_speed: 0.2,
            app_themes: std::collections::HashMap::new(),
            gradients: std::collections::HashMap::new(),
            animations: std::collections::HashMap::new(),
            widget_states: std::collections::HashMap::new(),
            ui_theme: oasis_ui::theme::Theme::dark(),
        }
    }
}
