//! Built-in skin definitions.
//!
//! Each skin is defined as embedded TOML constants. These provide functional
//! skins out of the box without requiring external skin directories.
//!
//! Skins are organized into three category modules:
//! - `classic` -- classic/retro skins (terminal, tactical, classic, retro-cga, win95)
//! - `modern` -- modern/desktop skins (desktop, modern, xp, macos, gnome, agent-terminal)
//! - `special` -- special/stylized skins (corrupted, cyberpunk, paper, solarized,
//!   vaporwave, highcontrast, altimit)
//!
//! Additionally, `generated` contains build-time generated loaders from TOML
//! directories in `skins/`. These are auto-generated by `build.rs` and produce
//! identical skins to the handwritten versions for the 12 TOML-based skins.

mod classic;
mod modern;
mod special;

/// Build-time generated skin loaders from `skins/` TOML directories.
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/builtin_generated.rs"));
}

pub use classic::{classic_skin, retro_cga_skin, tactical_skin, terminal_skin, win95_skin};
pub use modern::{agent_terminal_skin, desktop_skin, gnome_skin, macos_skin, modern_skin, xp_skin};
pub use special::{
    altimit_skin, corrupted_skin, cyberpunk_skin, highcontrast_skin, paper_skin, protanopia_skin,
    solarized_skin, tritanopia_skin, vaporwave_skin,
};

use oasis_types::error::Result;

use super::loader::Skin;

/// Load a built-in skin by name with optional inheritance.
///
/// If the skin's manifest specifies `inherits = "parent_name"`, the parent
/// skin is loaded first and its theme/layout fields fill in any missing
/// values in the child. Max inheritance depth is 3.
pub fn load_builtin(name: &str) -> Result<Skin> {
    load_builtin_recursive(name, 0)
}

fn load_builtin_raw(name: &str) -> Result<Skin> {
    match name {
        "classic" => classic_skin(),
        "terminal" => terminal_skin(),
        "tactical" => tactical_skin(),
        "corrupted" => corrupted_skin(),
        "desktop" => desktop_skin(),
        "agent-terminal" => agent_terminal_skin(),
        "modern" => modern_skin(),
        "xp" => xp_skin(),
        "macos" => macos_skin(),
        "gnome" => gnome_skin(),
        "retro-cga" => retro_cga_skin(),
        "cyberpunk" => cyberpunk_skin(),
        "paper" => paper_skin(),
        "win95" => win95_skin(),
        "solarized" => solarized_skin(),
        "vaporwave" => vaporwave_skin(),
        "highcontrast" => highcontrast_skin(),
        "altimit" => altimit_skin(),
        "protanopia" => protanopia_skin(),
        "tritanopia" => tritanopia_skin(),
        _ => Err(oasis_types::error::OasisError::Config(
            format!("unknown built-in skin: {name}").into(),
        )),
    }
}

fn load_builtin_recursive(name: &str, depth: u32) -> Result<Skin> {
    const MAX_DEPTH: u32 = 3;
    if depth > MAX_DEPTH {
        return Err(oasis_types::error::OasisError::Config(
            format!("skin inheritance depth exceeds {MAX_DEPTH} for '{name}'").into(),
        ));
    }

    let mut skin = load_builtin_raw(name)?;

    if let Some(ref parent_name) = skin.manifest.inherits {
        let parent = load_builtin_recursive(parent_name, depth + 1)?;
        skin.merge_theme_from(&parent);
    }

    Ok(skin)
}

/// List available built-in skin names.
pub fn builtin_names() -> &'static [&'static str] {
    &[
        "classic",
        "terminal",
        "tactical",
        "corrupted",
        "desktop",
        "agent-terminal",
        "modern",
        "xp",
        "macos",
        "gnome",
        "retro-cga",
        "cyberpunk",
        "paper",
        "win95",
        "solarized",
        "vaporwave",
        "highcontrast",
        "altimit",
        "protanopia",
        "tritanopia",
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use oasis_sdi::SdiRegistry;

    #[test]
    fn terminal_skin_loads() {
        let skin = terminal_skin().unwrap();
        assert_eq!(skin.manifest.name, "terminal");
        assert!(!skin.features.dashboard);
        assert!(skin.features.terminal);
        assert!(!skin.features.window_manager);
        assert!(skin.corrupted_modifiers.is_none());
        assert_eq!(skin.strings.prompt_format, "$> ");
    }

    #[test]
    fn terminal_skin_applies_layout() {
        let skin = terminal_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        assert!(sdi.contains("terminal_bg"));
        assert!(sdi.contains("terminal_output"));
        assert!(sdi.contains("terminal_prompt"));
    }

    #[test]
    fn tactical_skin_loads() {
        let skin = tactical_skin().unwrap();
        assert_eq!(skin.manifest.name, "tactical");
        assert!(!skin.features.dashboard);
        assert!(skin.features.terminal);
        assert!(!skin.features.window_manager);
        assert!(!skin.features.command_categories.is_empty());
        assert_eq!(skin.strings.prompt_format, "cmd> ");
    }

    #[test]
    fn tactical_skin_has_status_elements() {
        let skin = tactical_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        assert!(sdi.contains("status_bar"));
        assert!(sdi.contains("status_left"));
        assert!(sdi.contains("status_right"));
    }

    #[test]
    fn corrupted_skin_loads() {
        let skin = corrupted_skin().unwrap();
        assert_eq!(skin.manifest.name, "corrupted");
        assert!(skin.features.corrupted);
        assert!(skin.corrupted_modifiers.is_some());
        let mods = skin.corrupted_modifiers.as_ref().unwrap();
        assert_eq!(mods.position_jitter, 2);
        assert!(mods.text_garble_chance > 0.0);
    }

    #[test]
    fn corrupted_skin_has_glitch_overlay() {
        let skin = corrupted_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        assert!(sdi.contains("glitch_overlay"));
    }

    #[test]
    fn desktop_skin_loads() {
        let skin = desktop_skin().unwrap();
        assert_eq!(skin.manifest.name, "desktop");
        assert!(skin.features.window_manager);
        assert!(!skin.features.dashboard);
        assert_eq!(skin.manifest.screen_width, 800);
        assert_eq!(skin.manifest.screen_height, 600);
    }

    #[test]
    fn desktop_skin_has_wm_theme() {
        let skin = desktop_skin().unwrap();
        let wm = skin.theme.build_wm_theme();
        assert_eq!(wm.titlebar_height, 24);
        assert_eq!(wm.button_size, 16);
    }

    #[test]
    fn desktop_skin_has_taskbar() {
        let skin = desktop_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        assert!(sdi.contains("taskbar_bg"));
        assert!(sdi.contains("clock_display"));
    }

    #[test]
    fn load_builtin_all_names() {
        for name in builtin_names() {
            let skin = load_builtin(name).unwrap();
            assert_eq!(skin.manifest.name, *name);
        }
    }

    #[test]
    fn load_builtin_unknown_fails() {
        assert!(load_builtin("nonexistent").is_err());
    }

    #[test]
    fn swap_between_builtin_skins() {
        let terminal = terminal_skin().unwrap();
        let desktop = desktop_skin().unwrap();

        let mut sdi = SdiRegistry::new();
        terminal.apply_layout(&mut sdi);
        assert!(sdi.contains("terminal_bg"));
        assert!(sdi.contains("terminal_prompt"));

        let _new = Skin::swap(&terminal, desktop, &mut sdi);
        // Terminal-only objects removed, desktop objects created.
        assert!(!sdi.contains("terminal_bg"));
        assert!(!sdi.contains("terminal_prompt"));
        assert!(sdi.contains("desktop_bg"));
        assert!(sdi.contains("taskbar_bg"));
    }

    #[test]
    fn all_skins_have_boot_text() {
        for name in builtin_names() {
            let skin = load_builtin(name).unwrap();
            assert!(
                !skin.strings.boot_text.is_empty(),
                "{name} skin should have boot text"
            );
        }
    }

    #[test]
    fn all_skins_have_prompt() {
        for name in builtin_names() {
            let skin = load_builtin(name).unwrap();
            assert!(
                !skin.strings.prompt_format.is_empty(),
                "{name} skin should have prompt format"
            );
        }
    }

    #[test]
    fn agent_terminal_skin_loads() {
        let skin = agent_terminal_skin().unwrap();
        assert_eq!(skin.manifest.name, "agent-terminal");
        assert!(!skin.features.dashboard);
        assert!(skin.features.terminal);
        assert!(skin.features.file_browser);
        assert!(!skin.features.window_manager);
        assert!(!skin.features.command_categories.is_empty());
        assert!(
            skin.features
                .command_categories
                .contains(&"agent".to_string())
        );
        assert!(
            skin.features
                .command_categories
                .contains(&"mcp".to_string())
        );
        assert_eq!(skin.strings.prompt_format, "agent> ");
    }

    #[test]
    fn agent_terminal_skin_has_panels() {
        let skin = agent_terminal_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        assert!(sdi.contains("status_bar"));
        assert!(sdi.contains("agent_panel"));
        assert!(sdi.contains("session_panel"));
        assert!(sdi.contains("tamper_indicator"));
        assert!(sdi.contains("health_bar"));
        assert!(sdi.contains("terminal_output"));
        assert!(sdi.contains("terminal_prompt"));
    }

    #[test]
    fn agent_terminal_theme_colors() {
        let skin = agent_terminal_skin().unwrap();
        let bg = skin.theme.background_color();
        // Teal-ish dark background.
        assert_eq!(bg.r, 6);
        assert_eq!(bg.g, 13);
    }

    #[test]
    fn swap_terminal_to_agent_terminal() {
        let terminal = terminal_skin().unwrap();
        let agent = agent_terminal_skin().unwrap();

        let mut sdi = SdiRegistry::new();
        terminal.apply_layout(&mut sdi);
        assert!(sdi.contains("terminal_bg"));

        let _new = Skin::swap(&terminal, agent, &mut sdi);
        // Agent terminal has its own terminal_bg plus dashboard panels.
        assert!(sdi.contains("agent_panel"));
        assert!(sdi.contains("tamper_indicator"));
        assert!(sdi.contains("health_bar"));
    }

    #[test]
    fn modern_skin_loads() {
        let skin = modern_skin().unwrap();
        assert_eq!(skin.manifest.name, "modern");
        assert!(skin.features.dashboard);
        assert!(skin.features.terminal);
        assert!(skin.features.window_manager);
        assert!(skin.features.browser);
        assert_eq!(skin.manifest.screen_width, 480);
        assert_eq!(skin.manifest.screen_height, 272);
    }

    #[test]
    fn modern_skin_has_wm_theme() {
        let skin = modern_skin().unwrap();
        let wm = skin.theme.build_wm_theme();
        assert_eq!(wm.titlebar_radius, 6);
        assert!(wm.titlebar_gradient);
        assert_eq!(wm.frame_shadow_level, 2);
        assert_eq!(wm.frame_border_radius, 4);
        assert_eq!(wm.button_radius, 8);
    }

    #[test]
    fn modern_skin_has_extended_theme_fields() {
        let skin = modern_skin().unwrap();
        assert_eq!(skin.theme.border_radius, Some(6));
        assert_eq!(skin.theme.shadow_intensity, Some(2));
        assert_eq!(skin.theme.gradient_enabled, Some(true));
        assert!(skin.theme.surface.is_some());
        assert!(skin.theme.accent_hover.is_some());
    }

    #[test]
    fn modern_skin_applies_layout() {
        let skin = modern_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        assert!(sdi.contains("content_bg"));
    }

    #[test]
    fn modern_skin_content_bg_has_gradient() {
        let skin = modern_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        let obj = sdi.get("content_bg").unwrap();
        assert!(obj.gradient_top.is_some());
        assert!(obj.gradient_bottom.is_some());
    }

    #[test]
    fn desktop_skin_has_extended_wm_fields() {
        let skin = desktop_skin().unwrap();
        let wm = skin.theme.build_wm_theme();
        assert_eq!(wm.titlebar_radius, 4);
        assert_eq!(wm.frame_shadow_level, 1);
        assert_eq!(wm.frame_border_radius, 2);
        assert_eq!(wm.button_radius, 8);
    }

    #[test]
    fn desktop_skin_taskbar_has_gradient() {
        let skin = desktop_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        let obj = sdi.get("taskbar_bg").unwrap();
        assert!(obj.gradient_top.is_some());
        assert!(obj.gradient_bottom.is_some());
    }

    #[test]
    fn agent_terminal_panels_have_border_radius() {
        let skin = agent_terminal_skin().unwrap();
        let mut sdi = SdiRegistry::new();
        skin.apply_layout(&mut sdi);
        let panel = sdi.get("agent_panel").unwrap();
        assert_eq!(panel.border_radius, Some(4));
        let session = sdi.get("session_panel").unwrap();
        assert_eq!(session.border_radius, Some(4));
    }

    // -- Skin inheritance tests --

    #[test]
    fn load_builtin_with_inheritance_all_names() {
        // Ensure all built-in skins load without error (including inheritance).
        for name in builtin_names() {
            let skin = load_builtin(name);
            assert!(skin.is_ok(), "failed to load builtin skin '{name}'");
        }
    }

    #[test]
    fn load_builtin_with_inheritance_unknown_fails() {
        assert!(load_builtin("nonexistent").is_err());
    }

    #[test]
    fn no_builtin_has_inherits_by_default() {
        // Existing built-in skins don't use inheritance (none set `inherits`).
        for name in builtin_names() {
            let skin = load_builtin(name).unwrap();
            assert!(
                skin.manifest.inherits.is_none(),
                "built-in skin '{name}' has unexpected inherits field"
            );
        }
    }

    // -- Generated skin tests --

    #[test]
    fn all_generated_skins_load() {
        for name in super::generated::GENERATED_SKIN_NAMES {
            let result = super::generated::load_generated_skin(name);
            assert!(result.is_some(), "no generated loader for '{name}'");
            let skin = result.unwrap();
            assert!(
                skin.is_ok(),
                "generated skin '{name}' failed to load: {:?}",
                skin.err()
            );
            let skin = skin.unwrap();
            assert_eq!(skin.manifest.name, *name);
        }
    }

    #[test]
    fn generated_skins_match_handwritten_manifest() {
        // Compare generated skins against handwritten versions for the 12
        // TOML-based skins. Only compare fields that should be identical
        // (the TOML files are the source of truth for both).
        let toml_skins: &[&str] = &[
            "classic",
            "retro-cga",
            "win95",
            "xp",
            "macos",
            "gnome",
            "cyberpunk",
            "paper",
            "solarized",
            "vaporwave",
            "highcontrast",
            "altimit",
        ];

        for name in toml_skins {
            let generated = super::generated::load_generated_skin(name)
                .unwrap_or_else(|| panic!("no generated skin for '{name}'"))
                .unwrap_or_else(|e| panic!("generated '{name}' failed: {e}"));
            let hw = load_builtin_raw(name)
                .unwrap_or_else(|e| panic!("handwritten '{name}' failed: {e}"));

            // Manifest name must match.
            assert_eq!(
                generated.manifest.name, hw.manifest.name,
                "name mismatch for '{name}'"
            );

            // Strings must match.
            assert_eq!(
                generated.strings.prompt_format, hw.strings.prompt_format,
                "prompt_format mismatch for '{name}'"
            );
            assert_eq!(
                generated.strings.boot_text, hw.strings.boot_text,
                "boot_text mismatch for '{name}'"
            );
            assert_eq!(
                generated.strings.title, hw.strings.title,
                "title mismatch for '{name}'"
            );

            // Theme base colors must match.
            assert_eq!(
                generated.theme.background_color(),
                hw.theme.background_color(),
                "background color mismatch for '{name}'"
            );
            assert_eq!(
                generated.theme.primary_color(),
                hw.theme.primary_color(),
                "primary color mismatch for '{name}'"
            );

            // Features must match.
            assert_eq!(
                generated.features.dashboard, hw.features.dashboard,
                "dashboard mismatch for '{name}'"
            );
            assert_eq!(
                generated.features.terminal, hw.features.terminal,
                "terminal mismatch for '{name}'"
            );
            assert_eq!(
                generated.features.window_manager, hw.features.window_manager,
                "window_manager mismatch for '{name}'"
            );
        }
    }

    #[test]
    fn generated_skin_dispatch_unknown_returns_none() {
        assert!(super::generated::load_generated_skin("nonexistent").is_none());
    }
}
